### ISSUE TITLE
Missing a way to inherit input

### ISSUE THREAD

**Issue by Caralluin** [pgreze/kotlin-process#20]
As InputSource is a sealed class, which only translates to Redirect.from or Redirect.PIPE, I see no way to start the process with Redirect.INHERIT. Leaving stdin empty leads to using the default of Redirect.PIPE. This makes it very difficult to run interactive commands with dynamic input.

Perhaps you could add a `class Inherited : InputSource()` which is mapped to `ProcessBuilder.Redirect.INHERIT` by `toNative()`? Instead of "Inherit(ed)" it could also be named something like FromParent to be more in line with the other names.

**Comment by Caralluin** [comment]
I tried it successfully with the following small patch: [inherit-patch.txt](https://github.com/pgreze/kotlin-process/files/11056857/inherit-patch.txt). The naming of the new class/object & method is of course a matter of taste.

With this, it was possible for the called command to read console input.

**Comment by pgreze** [comment]
Thank you for your feedback!

Let me add your patch here, I'm gonna add it ASAP:
```patch
diff --git a/src/main/kotlin/com/github/pgreze/process/InputSource.kt b/src/main/kotlin/com/github/pgreze/process/InputSource.kt
index 258d686..bbe53ef 100644
--- a/src/main/kotlin/com/github/pgreze/process/InputSource.kt
+++ b/src/main/kotlin/com/github/pgreze/process/InputSource.kt
@@ -18,6 +18,8 @@ sealed class InputSource {
      */
     class FromStream(val handler: suspend (OutputStream) -> Unit) : InputSource()
 
+    object FromParent : InputSource()
+
     @Suppress("BlockingMethodInNonBlockingContext")
     companion object {
         @JvmStatic
@@ -35,10 +37,14 @@ sealed class InputSource {
         ): InputSource = FromStream { out ->
             inputStream.use { it.copyTo(out, bufferSize) }
         }
+
+        @JvmStatic
+        fun fromParent(): InputSource = FromParent
     }
 }
 
 internal fun InputSource.toNative() = when (this) {
     is InputSource.FromFile -> ProcessBuilder.Redirect.from(file)
     is InputSource.FromStream -> ProcessBuilder.Redirect.PIPE
+    is InputSource.FromParent -> ProcessBuilder.Redirect.INHERIT
 }
```
