### ISSUE TITLE
Close process on coroutine cancelation

### ISSUE THREAD

**Issue by Syer10** [pgreze/kotlin-process#5]
I have another app that I run alongside my application, and I want it to be closed with my application, for this currently I use Runtime.exec, but I was thinking of trying out this library as Runtime.exec has issues with the way I am using it. It doesn't seem to close the attached process on coroutine cancellation though, which I feel would fit with the way the library is built.

**Comment by pgreze** [comment]
(Sorry for the late answer...)
I agree with you, by default the process should be stopped when the coroutine is cancelled.
Let me investigate on the best way to handle cancellation in async calls.

**Comment by pgreze** [comment]
@Syer10 I just released the [version 1.3](https://github.com/pgreze/kotlin-process/releases/tag/v1.3) with cancellation support.

**Comment by pgreze** [comment]
@Syer10 I just released the [version 1.3](https://github.com/pgreze/kotlin-process/releases/tag/v1.3) with cancellation support.
